/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.freewebmovement

import org.json.JSONObject
import kotlin.test.Test

class APITest {
    @Test
    @Throws(InterruptedException::class)
    fun shouldGetQuota() {
        val username = "sammy"
        val password = "1234"
        val api = API()
        api.start(username, password);
        val quota: Quota? = api.quota;
        assert(quota != null);
        if (quota != null) {
            assert(quota.username == username)
        }
        if (quota != null) {
            assert(quota.quota.equals(0))
        }
        if (quota != null) {
            assert(quota.upload.equals(0))
        }
        if (quota != null) {
            assert(quota.download.equals(0))
        }
    }
    @Test
    @Throws(InterruptedException::class)
    fun shouldGetQuotaByOKAPI() {
        val username = "sammy"
        val password = "1234"
        val api = OKAPI()
        val quotaStr: String = api.quota(username, password)
        val quotaJSON = JSONObject(quotaStr)!!
        assert(quotaJSON.getString("username").equals(username))
        assert(quotaJSON.getInt("quota") === 0)
        assert(quotaJSON.getInt("upload") === 0)
        assert(quotaJSON.getInt("download") === 0)
    }
}
